name: Deploy to server 2

on: push

jobs:
  first_job:

    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
    #Crear un artifact
    - name: Generar archivo
      run: |
        echo "Archivo prueba, hola" >> test.log

    ##genera un archivo comprimido
    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: archivo-test
        path: test.log

  second_job:

    runs-on: ubuntu-latest
    needs: first_job

    #Descargar artefacto para poder leerlo desde otro job
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test
      
      - name: Cat file
        run: cat test.log


