# Directiva
name: Deploy to server

#Definir evento o lista de eventos con la directiva on:
on: push

jobs:
  #Definir un identificador
  first_job:
    #Definir sistema operativo o Maquina virtual asociada
    runs-on: ubuntu-latest

    steps:
    #Empiezan con un -
    #Puede ejecutar comando o acciones
    - name: Hola Mundo
      run: echo "Hola Mundo"

  second_jobs:
    #Condicionales
    #Utilizar contexto para condicionar
    if: ${{ github.ref == 'refs/heads/main' }}
    # se indica que second jobs se necesita que se haya completado needs, por lo que hace que se ejecuten secuencialmente, no paralelamente
    needs: first_job
    #Definir MC, cada job necesita su propia definicion
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo Segundo"

  #First y Second job se ejecutanparalelamente, al mismo tiempo, cuando no se tiene el needs en el segundo 
    


    