# Directiva
name: Deploy to server

#Definir evento o lista de eventos con la directiva on:
on: push

jobs:
  #Definir un identificador
  first_job:
    #Decalrar con name: "", un nombre para mostrar en git
    #Definir sistema operativo o Maquina virtual asociada
    runs-on: ubuntu-latest

    #variables de entorno
    env:
      #nombre variable : valor
      NAME: VariableGlobal

    steps:
    #Empiezan con un -
    #Puede ejecutar comando o acciones
    - name: Working dir
      run: ls -al

    #usar accion (chekout, situarte donde esta la accion)
    - name: Action
      #nombre de la accion: 1. nombre del repo de quien crea la accion, 2. nombre de la accion, 3. @version
      uses: actions/chekout@v4

    - name: Working dir after action
      run: ls -al
  second_jobs:
    #Condicionales
    #Utilizar contexto para condicionar
    if: ${{ github.ref == 'refs/heads/main' }}
    # se indica que second jobs se necesita que se haya completado needs, por lo que hace que se ejecuten secuencialmente, no paralelamente
    needs: first_job
    #Definir MC, cada job necesita su propia definicion
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo Segundo"
    
   

    


    