# Directiva
name: Deploy to server

#Definir evento o lista de eventos con la directiva on:
on: push

jobs:
  #Definir un identificador
  first_job:
    #Definir sistema operativo o Maquina virtual asociada
    runs-on: ubuntu-latest

    steps:
    #Empiezan con un -
    #Puede ejecutar comando o acciones
    - name: Hola Mundo
      run: echo "Hola Mundo"

  seconf_jobs:
    #Definir MC, cada job necesita su propia definicion
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo Segundo"


    